name       : python-notebook
version    : 6.4.10
release    : 9
source     :
    - https://github.com/jupyter/notebook/archive/refs/tags/6.4.10.tar.gz : 8fbdfc82a40dd84e744422cf44b0e01370edbdf6415baa1bb43dbb731fcee609
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : A web-based notebook environment for interactive computing
description: |
    The Jupyter Notebook is a web application that allows you to create and share documents that contain live code, equations, visualizations, and explanatory text. The Notebook has support for multiple programming languages, sharing, and interactive widgets.
networking : yes
builddeps  :
    - git
    - nodejs
rundeps    :
    - python-argon2-cffi
    - python-ipython_genutils
    - python-jinja
    - python-nbconvert
    - python-prometheus_client
    - python-send2trash
    - python-terminado
build      : |
    %python3_setup
install    : |
    %python3_install
