name       : python-notebook
version    : 6.5.2
release    : 11
source     :
    - https://github.com/jupyter/notebook/archive/refs/tags/v6.5.2.tar.gz : 4f8eb79767c628dad0b2d38a8781cd4eaa79656adff04f82a12055205d76bfbc
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : A web-based notebook environment for interactive computing
description: |
    The Jupyter Notebook is a web application that allows you to create and share documents that contain live code, equations, visualizations, and explanatory text. The Notebook has support for multiple programming languages, sharing, and interactive widgets.
networking : yes
builddeps  :
    - git
    - nodejs
rundeps    :
    - python-nbclassic
build      : |
    %python3_setup
install    : |
    %python3_install
